INCH_TO_METER = 0.0254
NUM_GONDOLA = 5
NUM_SHELF = 6
NUM_PLATE = 12
BODY_THRESH = 0.8
THRESHOLD = 0.2

VERBOSE = 0
DEBUG = 0
VIZ = 0

NAIVE_ASSOCIATION = 0
CE_ASSOCIATION = 1
CLOSEST_ASSOCIATION = 2
ASSOCIATION_TYPE = CLOSEST_ASSOCIATION

ARRANGEMENT_CONTRIBUTION = 0.8
WEIGHT_CONTRIBUTION = 1 - ARRANGEMENT_CONTRIBUTION
